function array (numUsers, bestNodeVec, bestNodeTypeVec, bestDistanceVec, bestPathLossVec, bestSinrDbVec, capacityMbpsVec, bestElevationDegVec, nodePowerWattsVec, energyPerBitUJVec)

userID = (1:numUsers)';
resultsTable = table(userID, bestNodeVec, bestNodeTypeVec, ...
    bestDistanceVec, bestPathLossVec, bestSinrDbVec, ...
    capacityMbpsVec, bestElevationDegVec, ...
    nodePowerWattsVec, energyPerBitUJVec, ...
    'VariableNames', {'User','ServingNode','ServingType', ...
    'Distance_m','PathLoss_dB','SINR_dB','Capacity_Mbps','SatElevation_deg', ...
    'NodePower_W','EnergyPerBit_uJ'});
disp(resultsTable)

end