function array (numUsers, bestNodeVec, bestNodeTypeVec, bestDistanceVec, bestPathLossVec, bestSnrDbVec, capacityMbpsVec, bestElevationDegVec)

userID = (1:numUsers)';
resultsTable = table(userID, bestNodeVec, bestNodeTypeVec, ...
    bestDistanceVec, bestPathLossVec, bestSnrDbVec, ...
    capacityMbpsVec, bestElevationDegVec, ...
    'VariableNames', {'User','ServingNode','ServingType', ...
    'Distance_m','PathLoss_dB','SNR_dB','Capacity_Mbps','SatElevation_deg'});
disp(resultsTable)

end